# Generated by Django 5.1.5 on 2025-01-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_user.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
