# Generated by Django 5.1.5 on 2025-01-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='MessageRead',
        ),
    ]
