# Generated by Django 5.1.5 on 2025-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0002_message_read_by_delete_messageread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
